---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudform.fullname" . }}-terminal
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudform.labels" . | nindent 4 }}
    app.kubernetes.io/component: terminal
spec:
  type: {{ .Values.terminalService.service.type }}
  ports:
  - port: {{ .Values.terminalService.service.port }}
    targetPort: ws
    protocol: TCP
    name: ws
  selector:
    {{- include "cloudform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: terminal