---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudform.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.portalApi.service.type }}
  ports:
  - port: {{ .Values.portalApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "cloudform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
