---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "cloud-portal.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.containers.namespace }}
  labels:
    {{- include "cloud-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: container-runtime