---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudform.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudform.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  keycloak-client-secret: "change-me-in-production"
  vault-token: "change-me-in-production"
  ## Convert to external secret