apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-admin-sa
  namespace: harbortech
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-admin-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: app-admin-sa
    namespace: harbortech
    