{{- if .Values.rbac.create }}
{{- range $key, $val := .Values.rbac }}
{{- if ne $key "create" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-rolebinding" $key }}
  namespace: {{ $.Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $val.name }}
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: ClusterRole
  name: argocd-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}