{{- if .Values.rbac.create -}}
{{- range $key, $val := .Values.rbac }}
{{- if ne $key "create" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-cluster-admin-binding" $key }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $val.name }}
    namespace: {{ $.Values.namespace }}
---
{{- end }}
{{- end }}
{{- end }}