{{- if .Values.rbac.create }}
---
# Role for Portal API in main namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-full-access" .Release.Name }}
  namespace: {{ .Values.namespace | default "harbortech" }}
  labels:
    app.kubernetes.io/name: {{ include "cloudform.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
{{- end }}