{{- if .Values.sharedServiceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sharedServiceAccount.name | default "cloudform-shared-sa" }}
  namespace: {{ .Values.namespace | default "harbortech" }}
  labels:
    app.kubernetes.io/name: {{ include "cloudform.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end }}
