{{- if .Values.rbac.create }}
---
# Portal API Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.portalApi.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.rbac.portalApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# Terminal Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.terminalService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudform.labels" . | nindent 4 }}
    app.kubernetes.io/component: terminal
  {{- with .Values.rbac.terminalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# Client Container Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.clientContainers.name }}
  namespace: {{ .Values.containers.namespace }}
  labels:
    {{- include "cloudform.labels" . | nindent 4 }}
    app.kubernetes.io/component: container-runtime
  {{- with .Values.rbac.clientContainers.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
# Cluster Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-admin-sa
  namespace: argo